// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// dht //
// --- //

#define dht_wrap_target 0
#define dht_wrap 25
#define dht_pio_version 0

static const uint16_t dht_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xe081, //  1: set    pindirs, 1                 
    0x80a0, //  2: pull   block                      
    0xe000, //  3: set    pins, 0                    
    0xa027, //  4: mov    x, osr                     
    0x0045, //  5: jmp    x--, 5                     
    0xe080, //  6: set    pindirs, 0                 
    0x20a0, //  7: wait   1 pin, 0                   
    0x2020, //  8: wait   0 pin, 0                   
    0x20a0, //  9: wait   1 pin, 0                   
    0x2020, // 10: wait   0 pin, 0                   
    0xe05f, // 11: set    y, 31                      
    0x20a0, // 12: wait   1 pin, 0                   
    0xe020, // 13: set    x, 0                       
    0x004f, // 14: jmp    x--, 15                    
    0x00ce, // 15: jmp    pin, 14                    
    0x4024, // 16: in     x, 4                       
    0x008c, // 17: jmp    y--, 12                    
    0xe047, // 18: set    y, 7                       
    0x20a0, // 19: wait   1 pin, 0                   
    0xe020, // 20: set    x, 0                       
    0x0056, // 21: jmp    x--, 22                    
    0x00d5, // 22: jmp    pin, 21                    
    0x4024, // 23: in     x, 4                       
    0x0093, // 24: jmp    y--, 19                    
    0x0002, // 25: jmp    2                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dht_program = {
    .instructions = dht_program_instructions,
    .length = 26,
    .origin = -1,
    .pio_version = dht_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dht_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dht_wrap_target, offset + dht_wrap);
    return c;
}
#endif

