// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// light //
// ----- //

#define light_wrap_target 0
#define light_wrap 2
#define light_pio_version 0

static const uint16_t light_program_instructions[] = {
            //     .wrap_target
    0x4001, //  0: in     pins, 1                    
    0x8020, //  1: push   block                      
    0x0000, //  2: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program light_program = {
    .instructions = light_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = light_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config light_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + light_wrap_target, offset + light_wrap);
    return c;
}
#endif

